// extensions/browser runtime api helpers and runtime behavior.
/** Re-exported browser plugin public API, starting with create Browser Tool. */
export { createBrowserTool } from "./src/browser-tool.js";
/** Re-exported browser plugin public API. */
export {
  applyBrowserProxyPaths,
  browserAct,
  browserArmDialog,
  browserArmFileChooser,
  type BrowserBridge,
  browserCloseTab,
  browserConsoleMessages,
  browserCreateProfile,
  type BrowserCreateProfileResult,
  browserDeleteProfile,
  type BrowserDeleteProfileResult,
  browserDoctor,
  type BrowserDoctorCheck,
  type BrowserDoctorReport,
  type BrowserExecutable,
  browserFocusTab,
  type BrowserFormField,
  browserNavigate,
  browserOpenTab,
  browserPdfSave,
  browserProfiles,
  browserResetProfile,
  type BrowserResetProfileResult,
  type BrowserRouteRegistrar,
  browserScreenshotAction,
  type BrowserServerState,
  browserSnapshot,
  browserStart,
  browserStatus,
  type BrowserStatus,
  browserStop,
  type BrowserTab,
  browserTabAction,
  browserTabs,
  type BrowserTransport,
  closeTrackedBrowserTabsForSessions,
  createBrowserControlContext,
  createBrowserRouteContext,
  createBrowserRouteDispatcher,
  createBrowserRuntimeState,
  DEFAULT_AI_SNAPSHOT_MAX_CHARS,
  DEFAULT_BROWSER_EVALUATE_ENABLED,
  DEFAULT_OPENCLAW_BROWSER_COLOR,
  DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME,
  DEFAULT_UPLOAD_DIR,
  ensureBrowserControlAuth,
  getBrowserControlState,
  getBrowserProfileCapabilities,
  installBrowserAuthMiddleware,
  installBrowserCommonMiddleware,
  isPersistentBrowserProfileMutation,
  movePathToTrash,
  normalizeBrowserFormField,
  normalizeBrowserFormFieldValue,
  normalizeBrowserRequestPath,
  parseBrowserMajorVersion,
  persistBrowserProxyFiles,
  type ProfileStatus,
  readBrowserVersion,
  redactCdpUrl,
  registerBrowserRoutes,
  resolveBrowserConfig,
  resolveBrowserControlAuth,
  type ResolvedBrowserConfig,
  type ResolvedBrowserProfile,
  resolveExistingPathsWithinRoot,
  resolveGoogleChromeExecutableForPlatform,
  resolveProfile,
  resolveRequestedBrowserProfile,
  runBrowserProxyCommand,
  type SnapshotResult,
  startBrowserBridgeServer,
  startBrowserControlServiceFromConfig,
  stopBrowserBridgeServer,
  stopBrowserControlService,
  stopBrowserRuntime,
  trackSessionBrowserTab,
  untrackSessionBrowserTab,
} from "./src/browser-runtime.js";
/** Re-exported browser plugin public API, starting with register Browser Cli. */
export { registerBrowserCli } from "./src/cli/browser-cli.js";
/** Re-exported browser plugin public API, starting with create Browser Plugin Service. */
export { createBrowserPluginService } from "./src/plugin-service.js";
/** Re-exported browser plugin public API, starting with handle Browser Gateway Request. */
export { handleBrowserGatewayRequest } from "./src/gateway/browser-request.js";
/** Re-exported browser plugin public API, starting with browser Handlers. */
export { browserHandlers } from "./src/gateway/browser-request.js";
/** Re-exported browser plugin public API. */
export {
  definePluginEntry,
  type OpenClawPluginApi,
  type OpenClawPluginToolContext,
  type OpenClawPluginToolFactory,
} from "openclaw/plugin-sdk/plugin-entry";
