// extensions/signal runtime api helpers and runtime behavior.
/** Re-exported signal plugin public API. */
export {
  applyAccountNameToChannelSection,
  buildBaseAccountStatusSnapshot,
  buildBaseChannelStatusSummary,
  buildChannelConfigSchema,
  type ChannelMessageActionAdapter,
  type ChannelPlugin,
  chunkText,
  collectStatusIssuesFromLastError,
  createDefaultChannelRuntimeState,
  DEFAULT_ACCOUNT_ID,
  deleteAccountFromConfigSection,
  detectBinary,
  emptyPluginConfigSchema,
  formatCliCommand,
  formatDocsLink,
  formatPairingApproveHint,
  getChatChannelMeta,
  installSignalCli,
  listEnabledSignalAccounts,
  listSignalAccountIds,
  looksLikeSignalTargetId,
  migrateBaseNameToDefaultAccount,
  monitorSignalProvider,
  normalizeAccountId,
  normalizeE164,
  normalizeSignalMessagingTarget,
  type OpenClawConfig,
  type OpenClawPluginApi,
  PAIRING_APPROVED_MESSAGE,
  type PluginRuntime,
  probeSignal,
  removeReactionSignal,
  resolveAllowlistProviderRuntimeGroupPolicy,
  resolveChannelMediaMaxBytes,
  resolveDefaultGroupPolicy,
  resolveDefaultSignalAccountId,
  type ResolvedSignalAccount,
  resolveSignalAccount,
  resolveSignalReactionLevel,
  sendMessageSignal,
  sendReactionSignal,
  setAccountEnabledInConfigSection,
  type SignalAccountConfig,
  SignalConfigSchema,
  signalMessageActions,
} from "./src/runtime-api.js";
/** Re-exported signal plugin public API, starting with set Signal Runtime. */
export { setSignalRuntime } from "./src/runtime.js";
