// Public speech-core SDK barrel re-exported for plugin-facing speech helpers.
/** Speech-core runtime helper exports from the plugin SDK surface. */
export {
  asBoolean,
  asFiniteNumber,
  asObject,
  assertOkOrThrowProviderError,
  canonicalizeSpeechProviderId,
  createProviderHttpError,
  extractProviderErrorDetail,
  extractProviderRequestId,
  formatProviderErrorPayload,
  formatProviderHttpErrorMessage,
  getSpeechProvider,
  listSpeechProviders,
  normalizeApplyTextNormalization,
  normalizeLanguageCode,
  normalizeSeed,
  normalizeSpeechProviderId,
  normalizeTtsAutoMode,
  parseTtsDirectives,
  readResponseTextLimited,
  requireInRange,
  resolveEffectiveTtsConfig,
  scheduleCleanup,
  summarizeText,
  trimToUndefined,
  truncateErrorDetail,
  TTS_AUTO_MODES,
} from "openclaw/plugin-sdk/speech-core";
/** Speech-core public types from the plugin SDK surface. */
export type {
  ResolvedTtsConfig,
  ResolvedTtsModelOverrides,
  SpeechDirectiveTokenParseContext,
  SpeechDirectiveTokenParseResult,
  SpeechListVoicesRequest,
  SpeechModelOverridePolicy,
  SpeechProviderConfig,
  SpeechProviderConfiguredContext,
  SpeechProviderOverrides,
  SpeechProviderPlugin,
  SpeechProviderPreparedSynthesis,
  SpeechProviderPrepareSynthesisContext,
  SpeechProviderResolveConfigContext,
  SpeechProviderResolveTalkConfigContext,
  SpeechProviderResolveTalkOverridesContext,
  SpeechSynthesisRequest,
  SpeechSynthesisStreamRequest,
  SpeechSynthesisStreamResult,
  SpeechSynthesisTarget,
  SpeechTelephonySynthesisRequest,
  SpeechVoiceOption,
  TtsConfigResolutionContext,
  TtsDirectiveOverrides,
  TtsDirectiveParseResult,
} from "openclaw/plugin-sdk/speech-core";
