// Discord payload API runtime facade exposes CJS enum constants to ESM tests.
import { createRequire } from "node:module";
import type * as DiscordPayloadApiTypes from "discord-api-types/payloads/v10";

const requireDiscordPayloadApiTypes = createRequire(import.meta.url);
const discordPayloadApiTypes = requireDiscordPayloadApiTypes(
  "discord-api-types/payloads/v10",
) as typeof DiscordPayloadApiTypes;

/** Runtime payload module loaded through Node's CommonJS resolver. */
export default discordPayloadApiTypes;
/** Re-exported Discord payload enum and constant values used by ESM tests. */
export const {
  APIApplicationCommandPermissionsConstant,
  ActivityFlags,
  ActivityLocationKind,
  ActivityPlatform,
  ActivityType,
  AllowedMentionsTypes,
  ApplicationCommandOptionType,
  ApplicationCommandPermissionType,
  ApplicationCommandType,
  ApplicationFlags,
  ApplicationIntegrationType,
  ApplicationRoleConnectionMetadataType,
  ApplicationWebhookEventStatus,
  ApplicationWebhookEventType,
  ApplicationWebhookType,
  AttachmentFlags,
  AuditLogEvent,
  AuditLogOptionsType,
  AutoModerationActionType,
  AutoModerationRuleEventType,
  AutoModerationRuleKeywordPresetType,
  AutoModerationRuleTriggerType,
  BaseThemeType,
  ButtonStyle,
  ChannelFlags,
  ChannelType,
  ComponentType,
  ConnectionService,
  ConnectionVisibility,
  EmbedFlags,
  EmbedMediaFlags,
  EmbedType,
  EntitlementType,
  EntryPointCommandHandlerType,
  ForumLayoutType,
  GuildDefaultMessageNotifications,
  GuildExplicitContentFilter,
  GuildFeature,
  GuildHubType,
  GuildMFALevel,
  GuildMemberFlags,
  GuildNSFWLevel,
  GuildOnboardingMode,
  GuildOnboardingPromptType,
  GuildPremiumTier,
  GuildScheduledEventEntityType,
  GuildScheduledEventPrivacyLevel,
  GuildScheduledEventRecurrenceRuleFrequency,
  GuildScheduledEventRecurrenceRuleMonth,
  GuildScheduledEventRecurrenceRuleWeekday,
  GuildScheduledEventStatus,
  GuildSystemChannelFlags,
  GuildVerificationLevel,
  GuildWidgetStyle,
  IntegrationExpireBehavior,
  InteractionContextType,
  InteractionResponseType,
  InteractionType,
  InviteFlags,
  InviteTargetType,
  InviteType,
  MembershipScreeningFieldType,
  MessageActivityType,
  MessageFlags,
  MessageReferenceType,
  MessageSearchAuthorType,
  MessageSearchEmbedType,
  MessageSearchHasType,
  MessageSearchSortMode,
  MessageType,
  NameplatePalette,
  OAuth2Scopes,
  OverwriteType,
  PermissionFlagsBits,
  PollLayoutType,
  PresenceUpdateStatus,
  RoleFlags,
  SKUFlags,
  SKUType,
  SelectMenuDefaultValueType,
  SeparatorSpacingSize,
  SortOrderType,
  StageInstancePrivacyLevel,
  StatusDisplayType,
  StickerFormatType,
  StickerType,
  SubscriptionStatus,
  TeamMemberMembershipState,
  TeamMemberRole,
  TextInputStyle,
  ThreadAutoArchiveDuration,
  ThreadMemberFlags,
  UnfurledMediaItemFlags,
  UnfurledMediaItemLoadingState,
  UserFlags,
  UserPremiumType,
  VideoQualityMode,
  WebhookType,
} = discordPayloadApiTypes;
